package com.junjun.pojo;

public class admmn extends admmnKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn010;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN003
     *
     * @return the value of ADMMN.MN003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn003() {
        return mn003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN003
     *
     * @param mn003 the value for ADMMN.MN003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn003(String mn003) {
        this.mn003 = mn003 == null ? null : mn003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN004
     *
     * @return the value of ADMMN.MN004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn004() {
        return mn004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN004
     *
     * @param mn004 the value for ADMMN.MN004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn004(String mn004) {
        this.mn004 = mn004 == null ? null : mn004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN005
     *
     * @return the value of ADMMN.MN005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn005() {
        return mn005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN005
     *
     * @param mn005 the value for ADMMN.MN005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn005(String mn005) {
        this.mn005 = mn005 == null ? null : mn005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN006
     *
     * @return the value of ADMMN.MN006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn006() {
        return mn006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN006
     *
     * @param mn006 the value for ADMMN.MN006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn006(String mn006) {
        this.mn006 = mn006 == null ? null : mn006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN007
     *
     * @return the value of ADMMN.MN007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn007() {
        return mn007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN007
     *
     * @param mn007 the value for ADMMN.MN007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn007(String mn007) {
        this.mn007 = mn007 == null ? null : mn007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN008
     *
     * @return the value of ADMMN.MN008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn008() {
        return mn008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN008
     *
     * @param mn008 the value for ADMMN.MN008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn008(String mn008) {
        this.mn008 = mn008 == null ? null : mn008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN009
     *
     * @return the value of ADMMN.MN009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn009() {
        return mn009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN009
     *
     * @param mn009 the value for ADMMN.MN009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn009(String mn009) {
        this.mn009 = mn009 == null ? null : mn009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN010
     *
     * @return the value of ADMMN.MN010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn010() {
        return mn010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN010
     *
     * @param mn010 the value for ADMMN.MN010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn010(String mn010) {
        this.mn010 = mn010 == null ? null : mn010.trim();
    }
}