package com.junjun.pojo;

public class admmk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMK.MK001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mk001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMK.MK002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mk002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMK.MK003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mk003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMK.MK004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mk004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMK.MK005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mk005;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMK.MK001
     *
     * @return the value of ADMMK.MK001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMk001() {
        return mk001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMK.MK001
     *
     * @param mk001 the value for ADMMK.MK001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMk001(String mk001) {
        this.mk001 = mk001 == null ? null : mk001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMK.MK002
     *
     * @return the value of ADMMK.MK002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMk002() {
        return mk002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMK.MK002
     *
     * @param mk002 the value for ADMMK.MK002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMk002(String mk002) {
        this.mk002 = mk002 == null ? null : mk002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMK.MK003
     *
     * @return the value of ADMMK.MK003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMk003() {
        return mk003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMK.MK003
     *
     * @param mk003 the value for ADMMK.MK003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMk003(String mk003) {
        this.mk003 = mk003 == null ? null : mk003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMK.MK004
     *
     * @return the value of ADMMK.MK004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMk004() {
        return mk004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMK.MK004
     *
     * @param mk004 the value for ADMMK.MK004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMk004(String mk004) {
        this.mk004 = mk004 == null ? null : mk004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMK.MK005
     *
     * @return the value of ADMMK.MK005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMk005() {
        return mk005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMK.MK005
     *
     * @param mk005 the value for ADMMK.MK005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMk005(String mk005) {
        this.mk005 = mk005 == null ? null : mk005.trim();
    }
}