package com.junjun.pojo;

public class admmnKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMN.MN002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mn002;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN001
     *
     * @return the value of ADMMN.MN001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn001() {
        return mn001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN001
     *
     * @param mn001 the value for ADMMN.MN001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn001(String mn001) {
        this.mn001 = mn001 == null ? null : mn001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMN.MN002
     *
     * @return the value of ADMMN.MN002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMn002() {
        return mn002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMN.MN002
     *
     * @param mn002 the value for ADMMN.MN002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMn002(String mn002) {
        this.mn002 = mn002 == null ? null : mn002.trim();
    }
}