package com.junjun.pojo;

public class admmm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMM.MM001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mm001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMM.MM002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mm002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMM.MM003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mm003;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMM.MM001
     *
     * @return the value of ADMMM.MM001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMm001() {
        return mm001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMM.MM001
     *
     * @param mm001 the value for ADMMM.MM001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMm001(String mm001) {
        this.mm001 = mm001 == null ? null : mm001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMM.MM002
     *
     * @return the value of ADMMM.MM002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMm002() {
        return mm002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMM.MM002
     *
     * @param mm002 the value for ADMMM.MM002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMm002(String mm002) {
        this.mm002 = mm002 == null ? null : mm002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMM.MM003
     *
     * @return the value of ADMMM.MM003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMm003() {
        return mm003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMM.MM003
     *
     * @param mm003 the value for ADMMM.MM003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMm003(String mm003) {
        this.mm003 = mm003 == null ? null : mm003.trim();
    }
}