package com.junjun.pojo;

public class admmg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMG.MG001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mg001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMG.MG002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mg002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMG.MG003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mg003;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMG.MG001
     *
     * @return the value of ADMMG.MG001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMg001() {
        return mg001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMG.MG001
     *
     * @param mg001 the value for ADMMG.MG001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMg001(String mg001) {
        this.mg001 = mg001 == null ? null : mg001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMG.MG002
     *
     * @return the value of ADMMG.MG002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMg002() {
        return mg002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMG.MG002
     *
     * @param mg002 the value for ADMMG.MG002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMg002(String mg002) {
        this.mg002 = mg002 == null ? null : mg002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMG.MG003
     *
     * @return the value of ADMMG.MG003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMg003() {
        return mg003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMG.MG003
     *
     * @param mg003 the value for ADMMG.MG003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMg003(String mg003) {
        this.mg003 = mg003 == null ? null : mg003.trim();
    }
}