package com.junjun.pojo;

public class admma {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMA.MA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ma007;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA001
     *
     * @return the value of ADMMA.MA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa001() {
        return ma001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA001
     *
     * @param ma001 the value for ADMMA.MA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa001(String ma001) {
        this.ma001 = ma001 == null ? null : ma001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA002
     *
     * @return the value of ADMMA.MA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa002() {
        return ma002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA002
     *
     * @param ma002 the value for ADMMA.MA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa002(String ma002) {
        this.ma002 = ma002 == null ? null : ma002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA003
     *
     * @return the value of ADMMA.MA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa003() {
        return ma003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA003
     *
     * @param ma003 the value for ADMMA.MA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa003(String ma003) {
        this.ma003 = ma003 == null ? null : ma003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA004
     *
     * @return the value of ADMMA.MA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa004() {
        return ma004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA004
     *
     * @param ma004 the value for ADMMA.MA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa004(String ma004) {
        this.ma004 = ma004 == null ? null : ma004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA005
     *
     * @return the value of ADMMA.MA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa005() {
        return ma005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA005
     *
     * @param ma005 the value for ADMMA.MA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa005(String ma005) {
        this.ma005 = ma005 == null ? null : ma005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA006
     *
     * @return the value of ADMMA.MA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa006() {
        return ma006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA006
     *
     * @param ma006 the value for ADMMA.MA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa006(String ma006) {
        this.ma006 = ma006 == null ? null : ma006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMA.MA007
     *
     * @return the value of ADMMA.MA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMa007() {
        return ma007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMA.MA007
     *
     * @param ma007 the value for ADMMA.MA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMa007(String ma007) {
        this.ma007 = ma007 == null ? null : ma007.trim();
    }
}