package com.junjun.pojo;

public class admmf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF501
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf501;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMF.MF502
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mf502;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF001
     *
     * @return the value of ADMMF.MF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf001() {
        return mf001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF001
     *
     * @param mf001 the value for ADMMF.MF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf001(String mf001) {
        this.mf001 = mf001 == null ? null : mf001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF002
     *
     * @return the value of ADMMF.MF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf002() {
        return mf002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF002
     *
     * @param mf002 the value for ADMMF.MF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf002(String mf002) {
        this.mf002 = mf002 == null ? null : mf002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF003
     *
     * @return the value of ADMMF.MF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf003() {
        return mf003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF003
     *
     * @param mf003 the value for ADMMF.MF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf003(String mf003) {
        this.mf003 = mf003 == null ? null : mf003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF004
     *
     * @return the value of ADMMF.MF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf004() {
        return mf004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF004
     *
     * @param mf004 the value for ADMMF.MF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf004(String mf004) {
        this.mf004 = mf004 == null ? null : mf004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF005
     *
     * @return the value of ADMMF.MF005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf005() {
        return mf005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF005
     *
     * @param mf005 the value for ADMMF.MF005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf005(String mf005) {
        this.mf005 = mf005 == null ? null : mf005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF006
     *
     * @return the value of ADMMF.MF006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf006() {
        return mf006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF006
     *
     * @param mf006 the value for ADMMF.MF006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf006(String mf006) {
        this.mf006 = mf006 == null ? null : mf006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF007
     *
     * @return the value of ADMMF.MF007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf007() {
        return mf007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF007
     *
     * @param mf007 the value for ADMMF.MF007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf007(String mf007) {
        this.mf007 = mf007 == null ? null : mf007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF010
     *
     * @return the value of ADMMF.MF010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf010() {
        return mf010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF010
     *
     * @param mf010 the value for ADMMF.MF010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf010(String mf010) {
        this.mf010 = mf010 == null ? null : mf010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF501
     *
     * @return the value of ADMMF.MF501
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf501() {
        return mf501;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF501
     *
     * @param mf501 the value for ADMMF.MF501
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf501(String mf501) {
        this.mf501 = mf501 == null ? null : mf501.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMF.MF502
     *
     * @return the value of ADMMF.MF502
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMf502() {
        return mf502;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMF.MF502
     *
     * @param mf502 the value for ADMMF.MF502
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMf502(String mf502) {
        this.mf502 = mf502 == null ? null : mf502.trim();
    }
}