package com.junjun.pojo;

public class admmj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMJ.MJ001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mj001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMJ.MJ002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mj002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMJ.MJ003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mj003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMMJ.MJ004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String mj004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMJ.MJ001
     *
     * @return the value of ADMMJ.MJ001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMj001() {
        return mj001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMJ.MJ001
     *
     * @param mj001 the value for ADMMJ.MJ001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMj001(String mj001) {
        this.mj001 = mj001 == null ? null : mj001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMJ.MJ002
     *
     * @return the value of ADMMJ.MJ002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMj002() {
        return mj002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMJ.MJ002
     *
     * @param mj002 the value for ADMMJ.MJ002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMj002(String mj002) {
        this.mj002 = mj002 == null ? null : mj002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMJ.MJ003
     *
     * @return the value of ADMMJ.MJ003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMj003() {
        return mj003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMJ.MJ003
     *
     * @param mj003 the value for ADMMJ.MJ003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMj003(String mj003) {
        this.mj003 = mj003 == null ? null : mj003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMMJ.MJ004
     *
     * @return the value of ADMMJ.MJ004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMj004() {
        return mj004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMMJ.MJ004
     *
     * @param mj004 the value for ADMMJ.MJ004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMj004(String mj004) {
        this.mj004 = mj004 == null ? null : mj004.trim();
    }
}