package com.junjun.pojo;

public class admml {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMML.ML001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ml001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMML.ML002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ml002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMML.ML003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ml003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMML.ML004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ml004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMML.ML001
     *
     * @return the value of ADMML.ML001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMl001() {
        return ml001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMML.ML001
     *
     * @param ml001 the value for ADMML.ML001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMl001(String ml001) {
        this.ml001 = ml001 == null ? null : ml001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMML.ML002
     *
     * @return the value of ADMML.ML002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMl002() {
        return ml002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMML.ML002
     *
     * @param ml002 the value for ADMML.ML002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMl002(String ml002) {
        this.ml002 = ml002 == null ? null : ml002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMML.ML003
     *
     * @return the value of ADMML.ML003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMl003() {
        return ml003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMML.ML003
     *
     * @param ml003 the value for ADMML.ML003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMl003(String ml003) {
        this.ml003 = ml003 == null ? null : ml003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMML.ML004
     *
     * @return the value of ADMML.ML004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getMl004() {
        return ml004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMML.ML004
     *
     * @param ml004 the value for ADMML.ML004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setMl004(String ml004) {
        this.ml004 = ml004 == null ? null : ml004.trim();
    }
}