package com.junjun.pojo;

public class syste {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te013;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE014
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te014;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE015
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te015;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE016
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE017
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTE.TE018
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String te018;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE001
     *
     * @return the value of SYSTE.TE001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe001() {
        return te001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE001
     *
     * @param te001 the value for SYSTE.TE001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe001(String te001) {
        this.te001 = te001 == null ? null : te001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE002
     *
     * @return the value of SYSTE.TE002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe002() {
        return te002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE002
     *
     * @param te002 the value for SYSTE.TE002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe002(String te002) {
        this.te002 = te002 == null ? null : te002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE003
     *
     * @return the value of SYSTE.TE003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe003() {
        return te003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE003
     *
     * @param te003 the value for SYSTE.TE003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe003(String te003) {
        this.te003 = te003 == null ? null : te003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE004
     *
     * @return the value of SYSTE.TE004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe004() {
        return te004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE004
     *
     * @param te004 the value for SYSTE.TE004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe004(String te004) {
        this.te004 = te004 == null ? null : te004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE005
     *
     * @return the value of SYSTE.TE005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe005() {
        return te005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE005
     *
     * @param te005 the value for SYSTE.TE005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe005(String te005) {
        this.te005 = te005 == null ? null : te005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE006
     *
     * @return the value of SYSTE.TE006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe006() {
        return te006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE006
     *
     * @param te006 the value for SYSTE.TE006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe006(String te006) {
        this.te006 = te006 == null ? null : te006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE007
     *
     * @return the value of SYSTE.TE007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe007() {
        return te007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE007
     *
     * @param te007 the value for SYSTE.TE007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe007(String te007) {
        this.te007 = te007 == null ? null : te007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE008
     *
     * @return the value of SYSTE.TE008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe008() {
        return te008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE008
     *
     * @param te008 the value for SYSTE.TE008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe008(String te008) {
        this.te008 = te008 == null ? null : te008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE009
     *
     * @return the value of SYSTE.TE009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe009() {
        return te009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE009
     *
     * @param te009 the value for SYSTE.TE009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe009(String te009) {
        this.te009 = te009 == null ? null : te009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE010
     *
     * @return the value of SYSTE.TE010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe010() {
        return te010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE010
     *
     * @param te010 the value for SYSTE.TE010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe010(String te010) {
        this.te010 = te010 == null ? null : te010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE011
     *
     * @return the value of SYSTE.TE011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe011() {
        return te011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE011
     *
     * @param te011 the value for SYSTE.TE011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe011(String te011) {
        this.te011 = te011 == null ? null : te011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE012
     *
     * @return the value of SYSTE.TE012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe012() {
        return te012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE012
     *
     * @param te012 the value for SYSTE.TE012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe012(String te012) {
        this.te012 = te012 == null ? null : te012.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE013
     *
     * @return the value of SYSTE.TE013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe013() {
        return te013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE013
     *
     * @param te013 the value for SYSTE.TE013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe013(String te013) {
        this.te013 = te013 == null ? null : te013.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE014
     *
     * @return the value of SYSTE.TE014
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe014() {
        return te014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE014
     *
     * @param te014 the value for SYSTE.TE014
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe014(String te014) {
        this.te014 = te014 == null ? null : te014.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE015
     *
     * @return the value of SYSTE.TE015
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe015() {
        return te015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE015
     *
     * @param te015 the value for SYSTE.TE015
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe015(String te015) {
        this.te015 = te015 == null ? null : te015.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE016
     *
     * @return the value of SYSTE.TE016
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe016() {
        return te016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE016
     *
     * @param te016 the value for SYSTE.TE016
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe016(String te016) {
        this.te016 = te016 == null ? null : te016.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE017
     *
     * @return the value of SYSTE.TE017
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe017() {
        return te017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE017
     *
     * @param te017 the value for SYSTE.TE017
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe017(String te017) {
        this.te017 = te017 == null ? null : te017.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTE.TE018
     *
     * @return the value of SYSTE.TE018
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTe018() {
        return te018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTE.TE018
     *
     * @param te018 the value for SYSTE.TE018
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTe018(String te018) {
        this.te018 = te018 == null ? null : te018.trim();
    }
}