package com.junjun.pojo;

public class systh {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTH.TH007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String th007;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH001
     *
     * @return the value of SYSTH.TH001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh001() {
        return th001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH001
     *
     * @param th001 the value for SYSTH.TH001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh001(String th001) {
        this.th001 = th001 == null ? null : th001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH002
     *
     * @return the value of SYSTH.TH002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh002() {
        return th002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH002
     *
     * @param th002 the value for SYSTH.TH002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh002(String th002) {
        this.th002 = th002 == null ? null : th002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH003
     *
     * @return the value of SYSTH.TH003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh003() {
        return th003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH003
     *
     * @param th003 the value for SYSTH.TH003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh003(String th003) {
        this.th003 = th003 == null ? null : th003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH004
     *
     * @return the value of SYSTH.TH004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh004() {
        return th004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH004
     *
     * @param th004 the value for SYSTH.TH004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh004(String th004) {
        this.th004 = th004 == null ? null : th004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH005
     *
     * @return the value of SYSTH.TH005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh005() {
        return th005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH005
     *
     * @param th005 the value for SYSTH.TH005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh005(String th005) {
        this.th005 = th005 == null ? null : th005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH006
     *
     * @return the value of SYSTH.TH006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh006() {
        return th006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH006
     *
     * @param th006 the value for SYSTH.TH006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh006(String th006) {
        this.th006 = th006 == null ? null : th006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTH.TH007
     *
     * @return the value of SYSTH.TH007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTh007() {
        return th007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTH.TH007
     *
     * @param th007 the value for SYSTH.TH007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTh007(String th007) {
        this.th007 = th007 == null ? null : th007.trim();
    }
}