package com.junjun.pojo;

public class systa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTA.TA010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String ta010;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA001
     *
     * @return the value of SYSTA.TA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa001() {
        return ta001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA001
     *
     * @param ta001 the value for SYSTA.TA001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa001(String ta001) {
        this.ta001 = ta001 == null ? null : ta001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA002
     *
     * @return the value of SYSTA.TA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa002() {
        return ta002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA002
     *
     * @param ta002 the value for SYSTA.TA002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa002(String ta002) {
        this.ta002 = ta002 == null ? null : ta002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA003
     *
     * @return the value of SYSTA.TA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa003() {
        return ta003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA003
     *
     * @param ta003 the value for SYSTA.TA003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa003(String ta003) {
        this.ta003 = ta003 == null ? null : ta003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA004
     *
     * @return the value of SYSTA.TA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa004() {
        return ta004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA004
     *
     * @param ta004 the value for SYSTA.TA004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa004(String ta004) {
        this.ta004 = ta004 == null ? null : ta004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA005
     *
     * @return the value of SYSTA.TA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa005() {
        return ta005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA005
     *
     * @param ta005 the value for SYSTA.TA005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa005(String ta005) {
        this.ta005 = ta005 == null ? null : ta005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA006
     *
     * @return the value of SYSTA.TA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa006() {
        return ta006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA006
     *
     * @param ta006 the value for SYSTA.TA006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa006(String ta006) {
        this.ta006 = ta006 == null ? null : ta006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA007
     *
     * @return the value of SYSTA.TA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa007() {
        return ta007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA007
     *
     * @param ta007 the value for SYSTA.TA007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa007(String ta007) {
        this.ta007 = ta007 == null ? null : ta007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA008
     *
     * @return the value of SYSTA.TA008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa008() {
        return ta008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA008
     *
     * @param ta008 the value for SYSTA.TA008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa008(String ta008) {
        this.ta008 = ta008 == null ? null : ta008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA009
     *
     * @return the value of SYSTA.TA009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa009() {
        return ta009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA009
     *
     * @param ta009 the value for SYSTA.TA009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa009(String ta009) {
        this.ta009 = ta009 == null ? null : ta009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTA.TA010
     *
     * @return the value of SYSTA.TA010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTa010() {
        return ta010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTA.TA010
     *
     * @param ta010 the value for SYSTA.TA010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTa010(String ta010) {
        this.ta010 = ta010 == null ? null : ta010.trim();
    }
}