package com.junjun.pojo;

public class systf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTF.TF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tf001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTF.TF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tf002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTF.TF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tf003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTF.TF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tf004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTF.TF001
     *
     * @return the value of SYSTF.TF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTf001() {
        return tf001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTF.TF001
     *
     * @param tf001 the value for SYSTF.TF001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTf001(String tf001) {
        this.tf001 = tf001 == null ? null : tf001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTF.TF002
     *
     * @return the value of SYSTF.TF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTf002() {
        return tf002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTF.TF002
     *
     * @param tf002 the value for SYSTF.TF002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTf002(String tf002) {
        this.tf002 = tf002 == null ? null : tf002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTF.TF003
     *
     * @return the value of SYSTF.TF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTf003() {
        return tf003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTF.TF003
     *
     * @param tf003 the value for SYSTF.TF003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTf003(String tf003) {
        this.tf003 = tf003 == null ? null : tf003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTF.TF004
     *
     * @return the value of SYSTF.TF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTf004() {
        return tf004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTF.TF004
     *
     * @param tf004 the value for SYSTF.TF004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTf004(String tf004) {
        this.tf004 = tf004 == null ? null : tf004.trim();
    }
}