package com.junjun.pojo;

public class systb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTB.TB009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tb009;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB001
     *
     * @return the value of SYSTB.TB001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb001() {
        return tb001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB001
     *
     * @param tb001 the value for SYSTB.TB001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb001(String tb001) {
        this.tb001 = tb001 == null ? null : tb001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB002
     *
     * @return the value of SYSTB.TB002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb002() {
        return tb002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB002
     *
     * @param tb002 the value for SYSTB.TB002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb002(String tb002) {
        this.tb002 = tb002 == null ? null : tb002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB003
     *
     * @return the value of SYSTB.TB003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb003() {
        return tb003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB003
     *
     * @param tb003 the value for SYSTB.TB003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb003(String tb003) {
        this.tb003 = tb003 == null ? null : tb003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB004
     *
     * @return the value of SYSTB.TB004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb004() {
        return tb004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB004
     *
     * @param tb004 the value for SYSTB.TB004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb004(String tb004) {
        this.tb004 = tb004 == null ? null : tb004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB005
     *
     * @return the value of SYSTB.TB005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb005() {
        return tb005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB005
     *
     * @param tb005 the value for SYSTB.TB005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb005(String tb005) {
        this.tb005 = tb005 == null ? null : tb005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB006
     *
     * @return the value of SYSTB.TB006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb006() {
        return tb006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB006
     *
     * @param tb006 the value for SYSTB.TB006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb006(String tb006) {
        this.tb006 = tb006 == null ? null : tb006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB007
     *
     * @return the value of SYSTB.TB007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb007() {
        return tb007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB007
     *
     * @param tb007 the value for SYSTB.TB007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb007(String tb007) {
        this.tb007 = tb007 == null ? null : tb007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB008
     *
     * @return the value of SYSTB.TB008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb008() {
        return tb008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB008
     *
     * @param tb008 the value for SYSTB.TB008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb008(String tb008) {
        this.tb008 = tb008 == null ? null : tb008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTB.TB009
     *
     * @return the value of SYSTB.TB009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTb009() {
        return tb009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTB.TB009
     *
     * @param tb009 the value for SYSTB.TB009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTb009(String tb009) {
        this.tb009 = tb009 == null ? null : tb009.trim();
    }
}