package com.junjun.pojo;

public class systc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTC.TC001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tc001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTC.TC002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tc002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTC.TC003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tc003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTC.TC004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String tc004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTC.TC001
     *
     * @return the value of SYSTC.TC001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTc001() {
        return tc001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTC.TC001
     *
     * @param tc001 the value for SYSTC.TC001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTc001(String tc001) {
        this.tc001 = tc001 == null ? null : tc001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTC.TC002
     *
     * @return the value of SYSTC.TC002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTc002() {
        return tc002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTC.TC002
     *
     * @param tc002 the value for SYSTC.TC002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTc002(String tc002) {
        this.tc002 = tc002 == null ? null : tc002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTC.TC003
     *
     * @return the value of SYSTC.TC003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTc003() {
        return tc003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTC.TC003
     *
     * @param tc003 the value for SYSTC.TC003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTc003(String tc003) {
        this.tc003 = tc003 == null ? null : tc003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTC.TC004
     *
     * @return the value of SYSTC.TC004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTc004() {
        return tc004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTC.TC004
     *
     * @param tc004 the value for SYSTC.TC004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTc004(String tc004) {
        this.tc004 = tc004 == null ? null : tc004.trim();
    }
}