package com.junjun.pojo;

public class systd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTD.TD013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    private String td013;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD001
     *
     * @return the value of SYSTD.TD001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd001() {
        return td001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD001
     *
     * @param td001 the value for SYSTD.TD001
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd001(String td001) {
        this.td001 = td001 == null ? null : td001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD002
     *
     * @return the value of SYSTD.TD002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd002() {
        return td002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD002
     *
     * @param td002 the value for SYSTD.TD002
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd002(String td002) {
        this.td002 = td002 == null ? null : td002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD003
     *
     * @return the value of SYSTD.TD003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd003() {
        return td003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD003
     *
     * @param td003 the value for SYSTD.TD003
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd003(String td003) {
        this.td003 = td003 == null ? null : td003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD004
     *
     * @return the value of SYSTD.TD004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd004() {
        return td004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD004
     *
     * @param td004 the value for SYSTD.TD004
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd004(String td004) {
        this.td004 = td004 == null ? null : td004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD005
     *
     * @return the value of SYSTD.TD005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd005() {
        return td005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD005
     *
     * @param td005 the value for SYSTD.TD005
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd005(String td005) {
        this.td005 = td005 == null ? null : td005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD006
     *
     * @return the value of SYSTD.TD006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd006() {
        return td006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD006
     *
     * @param td006 the value for SYSTD.TD006
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd006(String td006) {
        this.td006 = td006 == null ? null : td006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD007
     *
     * @return the value of SYSTD.TD007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd007() {
        return td007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD007
     *
     * @param td007 the value for SYSTD.TD007
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd007(String td007) {
        this.td007 = td007 == null ? null : td007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD008
     *
     * @return the value of SYSTD.TD008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd008() {
        return td008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD008
     *
     * @param td008 the value for SYSTD.TD008
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd008(String td008) {
        this.td008 = td008 == null ? null : td008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD009
     *
     * @return the value of SYSTD.TD009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd009() {
        return td009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD009
     *
     * @param td009 the value for SYSTD.TD009
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd009(String td009) {
        this.td009 = td009 == null ? null : td009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD010
     *
     * @return the value of SYSTD.TD010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd010() {
        return td010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD010
     *
     * @param td010 the value for SYSTD.TD010
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd010(String td010) {
        this.td010 = td010 == null ? null : td010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD011
     *
     * @return the value of SYSTD.TD011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd011() {
        return td011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD011
     *
     * @param td011 the value for SYSTD.TD011
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd011(String td011) {
        this.td011 = td011 == null ? null : td011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD012
     *
     * @return the value of SYSTD.TD012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd012() {
        return td012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD012
     *
     * @param td012 the value for SYSTD.TD012
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd012(String td012) {
        this.td012 = td012 == null ? null : td012.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTD.TD013
     *
     * @return the value of SYSTD.TD013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public String getTd013() {
        return td013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTD.TD013
     *
     * @param td013 the value for SYSTD.TD013
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    public void setTd013(String td013) {
        this.td013 = td013 == null ? null : td013.trim();
    }
}