package com.junjun.dao;

import com.junjun.pojo.admmj;

public interface admmjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String mj001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(admmj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(admmj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    admmj selectByPrimaryKey(String mj001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(admmj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMJ
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(admmj record);
}