package com.junjun.dao;

import com.junjun.pojo.admmm;

public interface admmmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String mm001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(admmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(admmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    admmm selectByPrimaryKey(String mm001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(admmm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMM
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(admmm record);
}