package com.junjun.dao;

import com.junjun.pojo.admmg;

public interface admmgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String mg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(admmg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(admmg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    admmg selectByPrimaryKey(String mg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(admmg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMG
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(admmg record);
}