package com.junjun.dao;

import com.junjun.pojo.admmn;
import com.junjun.pojo.admmnKey;

public interface admmnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(admmnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(admmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(admmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    admmn selectByPrimaryKey(admmnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(admmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMN
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(admmn record);
}