package com.junjun.dao;

import com.junjun.pojo.admmf;

public interface admmfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String mf001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(admmf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(admmf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    admmf selectByPrimaryKey(String mf001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(admmf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMMF
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(admmf record);
}