package com.junjun.dao;

import com.junjun.pojo.systh;

public interface systhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String th001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(systh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(systh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    systh selectByPrimaryKey(String th001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(systh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTH
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(systh record);
}