package com.junjun.dao;

import com.junjun.pojo.systc;

public interface systcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String tc001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(systc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(systc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    systc selectByPrimaryKey(String tc001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(systc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTC
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(systc record);
}