package com.junjun.dao;

import com.junjun.pojo.systb;

public interface systbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String tb001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(systb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(systb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    systb selectByPrimaryKey(String tb001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(systb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTB
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(systb record);
}