package com.junjun.dao;

import com.junjun.pojo.systa;

public interface systaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String ta001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(systa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(systa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    systa selectByPrimaryKey(String ta001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(systa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTA
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(systa record);
}