package com.junjun.dao;

import com.junjun.pojo.systd;

public interface systdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int deleteByPrimaryKey(String td001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insert(systd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int insertSelective(systd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    systd selectByPrimaryKey(String td001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKeySelective(systd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTD
     *
     * @mbggenerated Fri Jul 20 08:56:22 CST 2018
     */
    int updateByPrimaryKey(systd record);
}